BOT_DATASET_FOR_TRAINING_FILENAME = 'dataset_for_bot.json'
BOT_VECTORIZER_FILENAME = 'bot_vectorizer.bin'
BOT_MODEL_FILENAME = 'bot_model.bin'
BOT_TOKEN_FILENAME = 'token.txt'
BOT_ANEKDOT = 'anekdot_nikulin.txt'
BOT_TOKEN_OWM_FILENAME = 'token_owm.txt'